# generated by stubgen and modified by hand
from _typeshed import Incomplete
from typing import TypeAlias
from ._array_types import (
    AbstractArray as AbstractArray,
    UInt2 as UInt2, 
    UInt4 as UInt4, 
    UInt8 as UInt8, 
    UInt16 as UInt16, 
    UInt32 as UInt32, 
    UInt64 as UInt64, 
    Int2 as Int2, 
    Int4 as Int4, 
    Int8 as Int8, 
    Int16 as Int16, 
    Int32 as Int32, 
    Int64 as Int64, 
    Float8e4m3b11fnuz as Float8e4m3b11fnuz, 
    Float8e4m3fn as Float8e4m3fn, 
    Float8e4m3fnuz as Float8e4m3fnuz, 
    Float8e5m2 as Float8e5m2, 
    Float8e5m2fnuz as Float8e5m2fnuz, 
    BFloat16 as BFloat16, 
    Float16 as Float16, 
    Float32 as Float32, 
    Float64 as Float64, 
    Complex64 as Complex64, 
    Complex128 as Complex128, 
    Bool as Bool, 
    # UInt as UInt, 
    # Int as Int, 
    # Integer as Integer, 
    # Float as Float, 
    # Complex as Complex, 
    # Inexact as Inexact, 
    # Real as Real, 
    # Num as Num, 
    # Shaped as Shaped,   # not supported
    # Key as Key,   # not supported
    _AnonymousDim as _AnonymousDim,
    _AnonymousVariadicDim as _AnonymousVariadicDim,
    _NamedDim as _NamedDim,
    _NamedVariadicDim as _NamedVariadicDim,
    _FixedDim as _FixedDim,
    _SymbolicDim as _SymbolicDim,
)

PyTree: TypeAlias
check_equinox_version: bool
eqx_version: Incomplete
major: Incomplete
minor: Incomplete
patch: Incomplete
equinox_version: Incomplete
__version__: Incomplete
