from ._errors import AnnotationError as AnnotationError
from ._storage import clear_treeflatten_memo as clear_treeflatten_memo, clear_treepath_memo as clear_treepath_memo, get_shape_memo as get_shape_memo, set_shape_memo as set_shape_memo, set_treeflatten_memo as set_treeflatten_memo, set_treepath_memo as set_treepath_memo
from _typeshed import Incomplete
from typing import Generic

class _FakePyTree1(Generic[_T]): ...
class _FakePyTree2(Generic[_T, _S]): ...

class _MetaPyTree(type):
    def __call__(self, *args, **kwargs) -> None: ...
    def __instancecheck__(cls, obj): ...
    def __getitem__(cls, item): ...
    def __pdoc__(self, **kwargs): ...

PyTree: Incomplete
